[project]
name = "django-boilerplate"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "django-admin-adminlte>=1.0.6",
    "django>=5.1.3",
]
